# Generated by Django 4.2.16 on 2024-09-23 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_id', models.IntegerField()),
                ('user1', models.CharField(max_length=50)),
                ('user2', models.CharField(max_length=50)),
            ],
        ),
    ]
